### ISSUE TITLE
Explore the Response API

### ISSUE THREAD

**Issue by ro0NL** [ro0NL/symfony-http-responder#11]
There are more features then just statuscode/headers, respectively `Respond::withStatus/Headers()` on our side.

e.g. `Response::setCharset`, cache-control, etc.. Would be a waste if `Responder` requires this as raw headers.

Not sure if we want all these withers on Respond type, but worth exploring and see what API fits.

**Comment by kunicmarko20** [comment]
Probably worth adding the ones we know people use often and all the other can be added on request
