### ISSUE TITLE
Choose definitive responder API

### ISSUE THREAD

**Issue by ro0NL** [ro0NL/symfony-http-responder#18]
`respond(RespondSomething $r)` duplicates "Respond" term, which clutters its domain language.

- :confused: add the conventional prefix for Responds (current)
- :+1: make it first class domain language: `respond(new Json())` or `respondWith(new Json())`
- :rocket: make Responder an invokable: `return ($this->repsonder)(new RespondJson())`
- :eyes: something else..?

i tend to like option 2:) but `new Empty()` should be `new NoContent()` etc.

**Comment by kunicmarko20** [comment]
My opinion is that in this case `Respond` prefix/suffix is fine.

**Comment by kunicmarko20** [comment]
"Hey responder, respond with a json respond" maybe it should be a suffix instead of a prefix.

**Comment by ro0NL** [comment]
that's the issue.. "responder" "responds" with a "response"

response is a noun, respond its verb

**Comment by kunicmarko20** [comment]
but you are not passing it a response, you are passing it a _respond_
