### ISSUE TITLE
Add Forward respond (sub request)

### ISSUE THREAD

**Issue by ro0NL** [ro0NL/symfony-http-responder#26]

**Comment by linaori** [comment]
I'm pretty much convinced that this should not ever exist. Forwards from controllers make no sense and are a dangerous (performance heavy) way of doing what you can also achieve with proper service abstractions.

**Comment by ro0NL** [comment]
fair point, though i think we should weigh against convenience/compatibility.

i would like to put it in a bridge (http-kernel) for the compatibility part at least. Technically it's a form of responding we can support, so i'm not sure we should block it at the library level. Esp. since this is a first class feature in SF today :/

**Comment by ro0NL** [comment]
also see #5, for consistency a bridge to support http-kernel is considerable at least. For the comparison table (https://github.com/ro0NL/symfony-http-responder#comparison-table) that means 3 extra checkmarks :)
