### ISSUE TITLE
Add RespondException, RespondNotFound, RespondBadRequest

### ISSUE THREAD

**Issue by ro0NL** [ro0NL/symfony-http-responder#5]
to throw a HttpException

i think this one is important as we move the throw, by making it an implementation detail of the ExceptionResponder instead of controller/action.

**Comment by kunicmarko20** [comment]
`RespondException` interface as exception marker?

**Comment by ro0NL** [comment]
or generic (non-final) to throw any type of Exception

**Comment by ro0NL** [comment]
throw HttpException is tied to a kernel (not foundation). As such im not sure we should do this for now, other then solving portability.

for now the target is 100% http-kernel, until proven needed (e.g. someone using this lib standalone or a more purity-freak then me).

Closing for now.
